django/django-basics/Lesson03/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import homePage, aboutPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homePage, ),
    path('about/',  aboutPage,),
    path('posts/', include('posts.urls'))
]

django/django-basics/Lesson03/myproject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='list'),
    path('<slug:slug>', views.post_page, name='page')
]

django/django-basics/Lesson03/myproject/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    slug = models.SlugField()
    date= models.DateTimeField(auto_now_add=True)
    # Method to return the string representation of the model
    def __str__(self):
        return self.title

django/django-basics/Lesson03/myproject/myproject/views.py
from django.http import HttpResponse
from django.shortcuts import render
def homePage(request):
    # return HttpResponse("Hello, world. You're at the home page.")
    return render(request, 'home.html')


def aboutPage(request):
    # return HttpResponse("Hello, world. You're at the about page.")
    return render(request, 'about.html')

django/django-basics/Lesson03/myproject/posts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
# Create your views here.

def post_list(request):
    posts = Post.objects.all().order_by('-date')
    # Render the posts_list.html template with the posts context
    return render(request, 'posts/posts_list.html', {'posts': posts})
    # return render(request, 'posts/posts_list.html')

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})

django/django-basics/Lesson03/myproject/posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <section>
        <h1>{{ post.title }}</h1>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
    </section>
{% endblock %}

django/django-basics/Lesson03/myproject/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <section>
    <h1>Posts</h1>

    {% for post in posts %}
        <article class="post">
            <h2>
               <a href="{% url 'posts:page' slug=post.slug %}">{{ post.title }}</a>
            </h2>
            <p>{{ post.date }}</p>
            <p>{{ post.body }}</p>
        </article>
    {% endfor %}
</section>
{% endblock %}

django/django-basics/Lesson03/myproject/templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
{% endblock %}

django/django-basics/Lesson03/myproject/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
{% endblock %}

django/django-basics/Lesson03/myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/">🏠</a> | 
        <a href="/about">😀</a> | 
        <a href="{% url 'posts:list' %}">📰</a>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>